server:
  port: ${SERVER_PORT:8080}
camunda:
  bpm:
    client:
      base-url: ${MIL_ADAPTER_ENGINE_URL:http://localhost:8080}/engine-rest
      basic-auth:
        username: ${MIL_ADAPTER_ENGINE_ACCOUNT_USER:admin}
        password: ${MIL_ADAPTER_ENGINE_ACCOUNT_PASSWORD:AurigaNtt.2023}
rest-configuration:
  mil-authenticator-base-path: ${MIL_AUTHENTICATOR_BASE_PATH}
  mil-base-path: ${MIL_ADAPTER_MIL_BASE_PATH}
  id-pay-base-path: ${MIL_ADAPTER_ID_PAY_BASE_PATH}
  interceptor-logging-enabled: ${MIL_ADAPTER_ENABLE_INTERCEPTOR_LOGGING:true}
  log-engine-input-variables-enabled: ${MIL_ADAPTER_LOG_ENGINE_INPUT_VARIABLES:true}
  connection-request-timeout-milliseconds: ${MIL_ADAPTER_REST_CONNECTION_REQUEST_TIMEOUT_MILLISECONDS:1000}
  connection-response-timeout-milliseconds: ${MIL_ADAPTER_REST_CONNECTION_RESPONSE_TIMEOUT_MILLISECONDS:4000}
  max-retry: ${MIL_ADAPTER_REST_MAX_RETRY:0}
  retry-interval-milliseconds: ${MIL_ADAPTER_REST_RETRY_INTERVAL_MILLISECONDS:500}
  async-threshold: ${MIL_ADAPTER_ASYNC_RESPONSE_TIMEOUT:20000}
  model-base-path: ${MIL_ADAPTER_MODEL_BASE_PATH}
  auth:
    mil-authenticator-path: ${MIL_AUTHENTICATOR_RELATIVE_PATH:/api/v1/mil-authenticator/token}
    client-id: ${MIL_ADAPTER_MIL_AUTH_CLIENT_ID:}
    client-secret: ${MIL_ADAPTER_MIL_AUTH_CLIENT_SECRET:}
    grant-type: ${MIL_ADAPTER_MIL_AUTH_CLIENT_CREDENTIALS:client_credentials}
  definition-id-properties:
    method: GET
    url: /api/v1/model/bpmn/function/{functionType}/bank/{acquirerId}/branch/{branchId}/terminal/{terminalId}

spring:
  application:
    name: atm-layer-mil-adapter
  task:
    execution:
      pool:
        core-size: ${MIL_ADAPTER_CORE_SIZE:100}
        max-size: ${MIL_ADAPTER_MAX_SIZE:200}
        queue-capacity: ${MIL_ADAPTER_QUEUE_CAPACITY:500}

tracing:
  url: ${MIL_ADAPTER_TRACING_BACKEND_URL}

management:
  tracing:
    sampling:
      probability: 1.0



logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

id-pay:
  api-key: ${ID_PAY_API_KEY}
