server:
  port: ${SERVER_PORT:8080}
camunda:
  bpm:
    history-level: NONE
    client:
      base-url: ${MIL_ADAPTER_ENGINE_URL}/engine-rest
      lock-duration: ${MIL_ADAPTER_LOCK_DURATION:20000}
      disable-backoff-strategy: ${MIL_ADAPTER_DISABLE_BACKOFF_STRATEGY:true}
      async-response-timeout: ${MIL_ADAPTER_ASYNC_RESPONSE_TIMEOUT:20000}
      max-tasks: 15
      basic-auth:
        username: ${MIL_ADAPTER_ENGINE_ACCOUNT_USER}
        password: ${MIL_ADAPTER_ENGINE_ACCOUNT_PASSWORD}
rest-configuration:
  mil-authenticator-base-path: ${MIL_AUTHENTICATOR_BASE_PATH}
  mil-base-path: ${MIL_ADAPTER_MIL_BASE_PATH}
  id-pay-base-path: ${MIL_ADAPTER_ID_PAY_BASE_PATH}
  interceptor-logging-enabled: ${MIL_ADAPTER_ENABLE_INTERCEPTOR_LOGGING:true}
  log-engine-input-variables-enabled: ${MIL_ADAPTER_LOG_ENGINE_INPUT_VARIABLES:true}
  connection-request-timeout-milliseconds: ${MIL_ADAPTER_REST_CONNECTION_REQUEST_TIMEOUT_MILLISECONDS:1000}
  connection-response-timeout-milliseconds: ${MIL_ADAPTER_REST_CONNECTION_RESPONSE_TIMEOUT_MILLISECONDS:4000}
  max-retry: ${MIL_ADAPTER_REST_MAX_RETRY:1}
  retry-interval-milliseconds: ${MIL_ADAPTER_REST_RETRY_INTERVAL_MILLISECONDS:500}
  async-threshold: ${MIL_ADAPTER_ASYNC_RESPONSE_TIMEOUT:20000}
  model-base-path: ${MIL_ADAPTER_MODEL_BASE_PATH}
  auth:
    mil-authenticator-path: ${MIL_AUTHENTICATOR_RELATIVE_PATH:/api/v1/mil-authenticator/token}
    client-id: ${MIL_ADAPTER_MIL_AUTH_CLIENT_ID:}
    client-secret: ${MIL_ADAPTER_MIL_AUTH_CLIENT_SECRET:}
    grant-type: ${MIL_ADAPTER_MIL_AUTH_CLIENT_CREDENTIALS:client_credentials}
  definition-id-properties:
    method: GET
    url: /api/v1/model/bpmn/function/{functionType}/bank/{acquirerId}/branch/{branchId}/terminal/{terminalId}
cache-configuration:
  cache-name: ${MIL_ADAPTER_TOKEN_CACHE_NAME:token-cache}
  max-entries: ${MIL_ADAPTER_TOKEN_CACHE_MAX_ENTRIES:100}

spring:
  datasource:
    url: ${MIL_ADAPTER_ENGINE_DB_BASE_URL}/${MIL_ADAPTER_ENGINE_DB_NAME}?currentSchema=${MIL_ADAPTER_ENGINE_DB_SCHEMA}
    username: ${MIL_ADAPTER_ENGINE_DB_USERNAME}
    password: ${MIL_ADAPTER_ENGINE_DB_PASSWORD}
    driverClassName: ${MIL_ADAPTER_ENGINE_DB_DRIVER}
tracing:
  url: ${MIL_ADAPTER_TRACING_BACKEND_URL}

management:
  tracing:
    sampling:
      probability: 1.0

adapter-pool-configuration:
  rest:
    core-pool-size: ${MIL_ADAPTER_REST_POOL_CORE_POOL_SIZE:5}
    max-pool-size: ${MIL_ADAPTER_REST_POOL_MAX_POOL_SIZE:25}
    thread-name: ${MIL_ADAPTER_REST_POOL_THREAD_NAME:MILA-RestPool-}
    name: ${MIL_ADAPTER_REST_POOL_THREAD_NAME:restThreadPool}
  completion:
    core-pool-size: ${MIL_ADAPTER_COMPLETION_POOL_CORE_POOL_SIZE:5}
    max-pool-size: ${MIL_ADAPTER_COMPLETION_POOL_MAX_POOL_SIZE:25}
    thread-name: ${MIL_ADAPTER_COMPLETION_POOL_THREAD_NAME:MILA-CompPool-}
    name: ${MIL_ADAPTER_REST_POOL_THREAD_NAME:completionThreadPool}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
