apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: atm-layer-mil-adapter-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "pagopa-dev-atm-layer/rds/credentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: username
                objectAlias: username
              - path: password
                objectAlias: password
        - objectName: "pagopa-dev-atm-layer/camunda/credentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: WEB_USER
                objectAlias: WEB_USER
              - path: WEB_PASSWORD
                objectAlias: WEB_PASSWORD
        - objectName: "pagopa-dev-atm-layer/mil-auth/credentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: CLIENT_ID
                objectAlias: CLIENT_ID
              - path: CLIENT_SECRET
                objectAlias: CLIENT_SECRET
  secretObjects:
    - secretName: atm-layer-database
      type: Opaque
      data:
        - objectName: "username"  # reference the corresponding parameter
          key: DB_USERNAME
        - objectName: "password"  # reference the corresponding parameter
          key: DB_PASSWORD
    - secretName: atm-layer-webuser
      type: Opaque
      data:
        - objectName: "WEB_USER"  # reference the corresponding parameter
          key: WEB_USER
        - objectName: "WEB_PASSWORD"  # reference the corresponding parameter
          key: WEB_PASSWORD
    - secretName: atm-layer-mil-auth
      type: Opaque
      data:
        - objectName: "CLIENT_ID"  # reference the corresponding parameter
          key: CLIENT_ID
        - objectName: "CLIENT_SECRET"  # reference the corresponding parameter
          key: CLIENT_SECRET
